/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/webmodel-v1.glb --stdout 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/webmodel-v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.foam.geometry} material={materials['Material.001']} position={[0, 7, 0]} scale={6.292} />
      <mesh geometry={nodes.front_texture.geometry} material={materials['front model texture']} position={[0, 7, 0.16]} scale={6.292} />
      <mesh geometry={nodes.back_texture.geometry} material={materials['Material.004']} position={[0, 7, -0.16]} scale={6.292} />
      <mesh geometry={nodes.display.geometry} material={materials['tripo_mat_93f5d5d4-b371-4a7f-9c7e-aabf3af89880.001']} position={[0, 12, 0.15]} rotation={[Math.PI / 2, -1.553, Math.PI / 2]} scale={0.49} />
      <mesh geometry={nodes.sensor_icon_transparent.geometry} material={materials.sensor_icon_transparent} position={[0, 11, 0.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.756} />
    </group>
  )
}

useGLTF.preload('/webmodel-v1.glb')
