/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import {
  MODEL_URL,
  MODEL_TEXTURE_2_URL,
  MODEL_TEXTURE_3_URL,
  getDracoDecoderPath,
} from "./modelConstants.js";

/** Source GLBs are already authored at the correct world size. */
const MODEL_ROOT_SCALE = 0.1;

let dracoDecoderPathSet = false;
function ensureDracoDecoderPath() {
  if (dracoDecoderPathSet) return;
  dracoDecoderPathSet = true;
  useGLTF.setDecoderPath(getDracoDecoderPath());
}

function carpetModelUrl(design) {
  if (design === "texture2") return MODEL_TEXTURE_2_URL;
  if (design === "texture3") return MODEL_TEXTURE_3_URL;
  return MODEL_URL;
}

export const Carpet = React.forwardRef(function Carpet(
  // eslint-disable-next-line no-unused-vars -- passed from `Sence`; scroll drives camera, not this mesh.
  { displayRef, foamRef, onModelReady, progress, shadowsEnabled = true, design = "default", ...props },
  ref,
) {
  ensureDracoDecoderPath();
  const modelUrl = carpetModelUrl(design);
  const { nodes, materials } = useGLTF(modelUrl, true, false);

  useEffect(() => {
    onModelReady?.();
  }, [onModelReady]);

  const shadow = shadowsEnabled
    ? { castShadow: true, receiveShadow: true }
    : { castShadow: false, receiveShadow: false };

  return (
    <group ref={ref} {...props} dispose={null} scale={MODEL_ROOT_SCALE}>
      <mesh ref={foamRef} {...shadow} geometry={nodes.foam.geometry} material={materials["Material.001"]} />
      <mesh {...shadow} geometry={nodes.front_texture.geometry} material={materials["front model texture"]} />
      <mesh {...shadow} geometry={nodes.back_texture.geometry} material={materials["Material.004"]} />
      <mesh
        ref={displayRef}
        {...shadow}
        geometry={nodes.display.geometry}
        material={materials["tripo_mat_93f5d5d4-b371-4a7f-9c7e-aabf3af89880.001"]}
        position={[0, 12, 0.15]}
        rotation={[Math.PI / 2, -1.553, Math.PI / 2]}
      />
      <mesh
        {...shadow}
        geometry={nodes.sensor_icon_transparent.geometry}
        material={materials.sensor_icon_transparent}
        position={[0, 11, 0.18]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
});
