/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useCallback, useEffect, useMemo, useRef } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";
import {
  MODEL_URL,
  MODEL_TEXTURE_2_URL,
  MODEL_TEXTURE_3_URL,
  getDracoDecoderPath,
} from "./modelConstants.js";

const MODEL_ROOT_SCALE = 0.1;

/** Total length of the design-swap glitch. */
const DESIGN_SWAP_DURATION_MS = 720;
/** Intensity knobs for the premium glitch look (model-only, no scaling, no geometry distortion). */
const SHIMMER_STRENGTH = 0.85;
const SHIMMER_WIDTH = 0.9;
const WASH_STRENGTH = 0.55;
const CHROMA_SPLIT = 0.11;
const SATURATION_PULSE = 0.22;
const BRIGHTNESS_PULSE = 0.18;

/**
 * Shared uniforms — one instance drives every patched carpet material, so the glitch is coherent
 * across all meshes and survives route swaps while the GLTF material cache is warm.
 */
const SHARED_WAVE_UNIFORMS = {
  /** 0..1 bell envelope controlling overall glitch strength. */
  uGlitchAmount: { value: 0 },
  /** 0..1 linear progress driving the diagonal shimmer and wash travel. */
  uGlitchProgress: { value: 0 },
  /** Monotonic time driving tiny chroma flicker. */
  uGlitchTime: { value: 0 },
};
/** Materials we've already injected shader code into, so we never patch twice. */
const PATCHED_MATERIALS = new WeakSet();

function patchMaterialForWave(material) {
  if (!material || PATCHED_MATERIALS.has(material)) return;
  const prevOnBeforeCompile = material.onBeforeCompile?.bind(material);
  const prevCacheKey = material.customProgramCacheKey?.bind(material);

  material.onBeforeCompile = (shader) => {
    prevOnBeforeCompile?.(shader);
    shader.uniforms.uGlitchAmount = SHARED_WAVE_UNIFORMS.uGlitchAmount;
    shader.uniforms.uGlitchProgress = SHARED_WAVE_UNIFORMS.uGlitchProgress;
    shader.uniforms.uGlitchTime = SHARED_WAVE_UNIFORMS.uGlitchTime;

    /** Pass world-space position so the shimmer diagonal + radial wash stay coherent across every mesh. */
    shader.vertexShader =
      `
        varying vec3 vGlitchWorldPos;
      ` +
      shader.vertexShader.replace(
        "#include <begin_vertex>",
        `
          #include <begin_vertex>
          vGlitchWorldPos = (modelMatrix * vec4(position, 1.0)).xyz;
        `,
      );

    shader.fragmentShader =
      `
        uniform float uGlitchAmount;
        uniform float uGlitchProgress;
        uniform float uGlitchTime;
        varying vec3 vGlitchWorldPos;
      ` +
      shader.fragmentShader.replace(
        "#include <dithering_fragment>",
        `
          #include <dithering_fragment>
          if (uGlitchAmount > 0.001) {
            vec3 c = gl_FragColor.rgb;

            /** --- Pulse: desaturate briefly then settle; slight brightness wobble (mimics the original CSS filter pulse). */
            vec3 luma = vec3(dot(c, vec3(0.299, 0.587, 0.114)));
            float satShift = sin(uGlitchProgress * 3.14159);
            c = mix(c, luma, satShift * uGlitchAmount * ${SATURATION_PULSE.toFixed(3)});
            float bPulse = 1.0 + sin(uGlitchProgress * 6.2832) * uGlitchAmount * ${BRIGHTNESS_PULSE.toFixed(3)};
            c *= bPulse;

            /** --- Diagonal shimmer sweep (mimics the ::after overlay sweep from the original CSS). */
            float diag = dot(vGlitchWorldPos.xy, vec2(0.55, 0.75));
            float sweepPos = mix(-2.4, 2.4, uGlitchProgress);
            float shimmer = smoothstep(${SHIMMER_WIDTH.toFixed(3)}, 0.0, abs(diag - sweepPos));
            c += vec3(1.0) * shimmer * uGlitchAmount * ${SHIMMER_STRENGTH.toFixed(3)};

            /** --- Radial wash from model center (mimics the ::before radial gradient in the original CSS). */
            float dist = length(vGlitchWorldPos.xy - vec2(0.0, 0.2));
            float washEdge = mix(0.2, 1.6, uGlitchProgress);
            float wash = smoothstep(washEdge, washEdge * 0.25, dist);
            c += vec3(0.92, 0.95, 1.0) * wash * satShift * uGlitchAmount * ${WASH_STRENGTH.toFixed(3)};

            /** --- Subtle RGB chroma split so the transition still reads as "digital" without looking ugly. */
            float chromaFlicker = 0.6 + 0.4 * sin(uGlitchTime * 40.0);
            float split = uGlitchAmount * ${CHROMA_SPLIT.toFixed(3)} * chromaFlicker;
            c.r += split;
            c.b -= split * 0.9;

            gl_FragColor.rgb = c;
          }
        `,
      );
  };

  /** Distinct cache key so three.js compiles our patched variant separately from any unpatched usage. */
  material.customProgramCacheKey = () => (prevCacheKey?.() ?? "") + "|carpetGlitchPatch_v4";
  material.needsUpdate = true;
  PATCHED_MATERIALS.add(material);
}

function carpetModelUrl(design) {
  if (design === "texture2") return MODEL_TEXTURE_2_URL;
  if (design === "texture3") return MODEL_TEXTURE_3_URL;
  return MODEL_URL;
}

export const Carpet = React.forwardRef(function Carpet(
  // eslint-disable-next-line no-unused-vars -- passed from `Sence`; scroll drives camera, not this mesh.
  { displayRef, foamRef, onModelReady, progress, shadowsEnabled = true, design = "default", ...props },
  ref,
) {
  const configureDraco = useCallback((loader) => {
    const draco = new DRACOLoader();
    draco.setDecoderPath(getDracoDecoderPath());
    /** Keep worker count low to avoid CPU spikes on weaker devices. */
    draco.setWorkerLimit(1);
    loader.setDRACOLoader(draco);
  }, []);

  const modelUrl = carpetModelUrl(design);
  const { nodes, materials } = useGLTF(modelUrl, configureDraco, false);

  useEffect(() => {
    onModelReady?.();
  }, [onModelReady]);

  /** Patch every material for this design the moment they arrive from the GLTF cache. */
  useMemo(() => {
    if (!materials) return;
    Object.values(materials).forEach(patchMaterialForWave);
  }, [materials]);

  /** Hero canvas uses `frameloop="demand"`, so drive invalidate() during the glitch window. */
  const invalidate = useThree((s) => s.invalidate);
  const glitchStartRef = useRef(null);
  const prevDesignRef = useRef(design);

  useEffect(() => {
    if (prevDesignRef.current === design) return;
    prevDesignRef.current = design;
    glitchStartRef.current = performance.now();
    let raf = 0;
    const drive = () => {
      invalidate();
      const start = glitchStartRef.current;
      if (start != null && performance.now() - start < DESIGN_SWAP_DURATION_MS + 40) {
        raf = requestAnimationFrame(drive);
      }
    };
    raf = requestAnimationFrame(drive);
    return () => {
      if (raf) cancelAnimationFrame(raf);
    };
  }, [design, invalidate]);

  useFrame((_, delta) => {
    const start = glitchStartRef.current;
    const u = SHARED_WAVE_UNIFORMS;
    if (start == null) {
      if (u.uGlitchAmount.value !== 0) u.uGlitchAmount.value = 0;
      if (u.uGlitchProgress.value !== 0) u.uGlitchProgress.value = 0;
      return;
    }
    const elapsed = performance.now() - start;
    if (elapsed >= DESIGN_SWAP_DURATION_MS) {
      u.uGlitchAmount.value = 0;
      u.uGlitchProgress.value = 0;
      glitchStartRef.current = null;
      return;
    }
    const t = elapsed / DESIGN_SWAP_DURATION_MS;
    /** Linear progress drives the diagonal shimmer sweep + radial wash expansion. */
    u.uGlitchProgress.value = t;
    /** Bell envelope with a tiny flicker for the "digital" pulse feel — smooth entry/exit, no harsh snap. */
    const env = Math.sin(t * Math.PI);
    const flicker = 0.9 + 0.1 * Math.sin(elapsed * 0.08);
    u.uGlitchAmount.value = env * env * (3 - 2 * env) * flicker;
    u.uGlitchTime.value += delta;
  });

  const shadow = shadowsEnabled
    ? { castShadow: true, receiveShadow: true }
    : { castShadow: false, receiveShadow: false };

  return (
    <group ref={ref} {...props} dispose={null} scale={MODEL_ROOT_SCALE}>
      <mesh ref={foamRef} {...shadow} geometry={nodes.foam.geometry} material={materials["Material.001"]} />
      <mesh {...shadow} geometry={nodes.front_texture.geometry} material={materials["front model texture"]} />
      <mesh {...shadow} geometry={nodes.back_texture.geometry} material={materials["Material.004"]} />
      <mesh
        ref={displayRef}
        {...shadow}
        geometry={nodes.display.geometry}
        material={materials["tripo_mat_93f5d5d4-b371-4a7f-9c7e-aabf3af89880.001"]}
        position={[0, 12, 0.15]}
        rotation={[Math.PI / 2, -1.553, Math.PI / 2]}
      />
      <mesh
        {...shadow}
        geometry={nodes.sensor_icon_transparent.geometry}
        material={materials.sensor_icon_transparent}
        position={[0, 11, 0.18]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
});
