/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

const MODEL_URL = '/webmodel-v2.glb'

/** Hero camera paths in `Sence.jsx` assume ~unit-scale framing; GLB mesh scales are much larger. */
const MODEL_ROOT_SCALE = 0.1

export const Carpet = React.forwardRef(function Carpet(
  // eslint-disable-next-line no-unused-vars -- `Sence` passes scroll progress; not applied to the mesh.
  { displayRef, foamRef, onModelReady, progress, ...props },
  ref,
) {
  const { nodes, materials } = useGLTF(MODEL_URL)

  useEffect(() => {
    onModelReady?.()
  }, [onModelReady])

  return (
    <group ref={ref} {...props} dispose={null} scale={MODEL_ROOT_SCALE}>
      <mesh
        ref={foamRef}
        castShadow
        receiveShadow
        geometry={nodes.foam.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.front_texture.geometry}
        material={materials['front model texture']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.back_texture.geometry}
        material={materials['Material.004']}
      />
      <mesh
        ref={displayRef}
        castShadow
        receiveShadow
        geometry={nodes.display.geometry}
        material={materials['tripo_mat_93f5d5d4-b371-4a7f-9c7e-aabf3af89880.001']}
        position={[0, 12, 0.15]}
        rotation={[Math.PI / 2, -1.553, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sensor_icon_transparent.geometry}
        material={materials.sensor_icon_transparent}
        position={[0, 11, 0.18]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
})

useGLTF.preload(MODEL_URL)

/** Same geometry as `Carpet`; use when you only need the static gltfjsx shape. */
export function Model(props) {
  return <Carpet {...props} />
}
